export const DELETE_MOVIE_REQUEST_START = 'DELETE_MOVIE_REQUEST_START';
export const DELETE_MOVIE_REQUEST_SUCCESS = 'DELETE_MOVIE_REQUEST_SUCCESS';
export const DELETE_MOVIE_REQUEST_ERROR = 'DELETE_MOVIE_REQUEST_ERROR';
