export const ADD_MOVIE_REQUEST_START = 'ADD_MOVIE_REQUEST_START';
export const ADD_MOVIE_REQUEST_SUCCESS = 'ADD_MOVIE_REQUEST_SUCCESS';
export const ADD_MOVIE_REQUEST_ERROR = 'ADD_MOVIE_REQUEST_ERROR';
