export const EDIT_MOVIE_REQUEST_START = 'EDIT_MOVIE_REQUEST_START';
export const EDIT_MOVIE_REQUEST_SUCCESS = 'EDIT_MOVIE_REQUEST_SUCCESS';
export const EDIT_MOVIE_REQUEST_ERROR = 'EDIT_MOVIE_REQUEST_ERROR';
