export const GET_MOVIE_REQUEST_START = 'GET_MOVIE_REQUEST_START';
export const GET_MOVIE_REQUEST_SUCCESS = 'GET_MOVIE_REQUEST_SUCCESS';
export const GET_MOVIE_REQUEST_ERROR = 'GET_MOVIE_REQUEST_ERROR';
